name=xphs1903
version=2026.8.1
author=Émile Jetzer emile.jetzer@polymtl.ca,Jacques Massicotte jacques-2.massicotte@polymtl.ca
maintainer=Émile Jetzer emile.jetzer@polymtl.ca
sentence=Faciliter le développement de systèmes d'acquisition dans le cours PHS1903 à Polytechnique Montréal.
paragraph=Le module contient des définitions de fonctions et de classes par projet et utilité, pour faciliter le travail des étudiants.
category=Other
url=https://github.com/ejetzer/x.phs1903
architectures=megaavr
includes=adc1903.h,fft1903.h,xphs1903.h,serie.h,journal.h,broche.h,chrono.h
depends=ArduinoFFT,Logger,ArduinoSTL
