version: 2.0.1
build:
  os: ubuntu-latest
  tools:
    python: "3.14"
    # You can also specify other tool versions:
    # nodejs: "16"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/src/conf.py

# Dependencies required to build your docs
python:
   install:
   - requirements: docs/src/requirements.txt
