name=xphs1903
version=1.2.1
author=emile.jetzer@polymtl.ca
maintainer=emile.jetzer@polymtl.ca
sentence=Faciliter le développement de systèmes d'acquisition dans le cours PHS1903 à Polytechnique Montréal.
paragraph=Le module contient des définitions de fonctions et de classes par projet et utilité, pour faciliter le travail des étudiants.
category=Other
url=https://github.com/ejetzer/x.phs1903
architectures=*
includes=xphs1903.h
depends=