# https://packaging.python.org/en/latest/

[project]
name = "x.phs1903"
requires-python = ">=3.14"
dynamic = ["version", "dependencies"]
authors = [
  {name = "Émile Jetzer", email = "emile.jetzer@polymtl.ca"},
  {name = "Jacques Massicotte", email = "jacques-2.massicotte@polymtl.ca"},
]
license-files = ["LICENSE"]
readme = "README.rst"
classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 2 - Pre-Alpha",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Intended Audience :: Education",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Natural Language :: French",
  "Programming Language :: C++",
  "Programming Language :: C",
  "Programming Language :: Python :: 3.14",
  "Topic :: Education",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Software Development :: Embedded Systems",
]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Repository = "https://www.github.com/ejetzer/x.phs1903"

[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=8", "twine", "clang", "build"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["xphs1903*"]
exclude = ["arduino"]
