# https://mg.readthedocs.io/latexmk.html

@default_files = ("xphs1903");

$aux_dir = '.';
$out_dir = '.';

$pdf_mode = 4; # LuaLaTeX
$recorder = 1;

$force_mode = 1;
$silent = 0;

$use_make_for_missing_files = 1;

# $makeindex = 'xindex %O -o %D %S';

# Tiré du fichier généré par défaut
$lualatex = 'lualatex --shell-escape' . $ENV{'LATEXOPTS'} . ' %O %S';
#$makeindex = 'makeindex -s python.ist %O -o %D %S'
$makeindex = 'xindex -c sphinx -l fr %O -o %D %S';
add_cus_dep( "glo", "gls", 0, "makeglo" );
sub makeglo {
 #return system( "makeindex -s gglo.ist -o '$_[0].gls' '$_[0].glo'" );
 return system( "xindex -c sphinx -l fr -o '$_[0].gls' '$_[0].glo'" );
}
