version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.14"
    # You can also specify other tool versions:
    # nodejs: "16"
  #apt_packages:
  #- libclang-14-dev

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/src/conf.py

# Dependencies required to build your docs
python:
   install:
   - requirements: docs/src/requirements.txt
