name: Build everything

on:
  push:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: ajouter deadsnake
        run: sudo add-apt-repository ppa:deadsnakes/ppa
      
      - name: mettre apt à jour
        run: sudo apt-get update -y

      - name: installer zsh
        run: sudo apt-get install -y zsh
      
      - name: installer python
        run: sudo apt-get install -y python3.14
      
      - name: installer libclang
        run: sudo apt-get install -y libclang-14-dev
      
      - name: installer TeXlive
        run: sudo apt-get install -y texlive-full
      
      - name: installer pipenv
        run: python3.14 -m pip install pipenv

  build:
    runs-on: ubuntu-latest
    needs:
      - setup

    steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: installer le venv
          run: pipenv install
        
        - name: assembler sdist python
          run: pipenv run build --sdist .build
        
        - name: assembler wheel python
          run: pipenv run build --wheel .build

        - name: assembler module arduino
          run: make -C .github arduino
        
        - name: compiler doc html
          run: pipenv run sphinx-build -M singlehtml docs/src .build
        
        - name: assembler doc LaTeX
          run: pipenv run sphinx-build -M latex docs/src .build
        
        - name: compiler doc LaTeX
          run: make -C .github pdf
        
        - name: assembler les exemples python
          run: tar -c -s /src\/xphs1903\/// -f .build/python-demo.zip src/xphs1903/demos/*
        
        - name: assembler les exemples arduino
          run: tar -c -s /src\/arduino\/examples\/// -f .build/arduino-demo.zip src/arduino/examples/*
    
  load:
    runs-on: ubuntu-latest
    needs:
      - build
    
    steps:
        - name: charger sdist python
          uses: actions/upload-artifact@v4
          with:
            name: xphs1903-sdist
            path: .build/x_phs1903-*.tar.gz
        
        - name: charger wheel python
          uses: actions/upload-artifact@v4
          with:
            name: xphs1903-wheel
            path: .build/x_phs1903-*.whl
        
        - name: charger module arduino
          uses: actions/upload-artifact@v4
          with:
            name: xphs1903-arduino
            path: .build/xphs1903.zip
        
        - name: charger doc
          uses: actions/upload-artifact@v4
          with:
            name: xphs1903-doc
            path: |
              .build/singlehtml
              .build/latexpdf/*.pdf
        
        - name: charger les exemples
          uses: actions/upload-artifact@v4
          with:
            name: xphs1903-eg
            path: .build/*-demo.zip
