name: Build everything

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: installer zsh
          run: apt-get install zsh

        - name: Tout compiler
          run: make github-build
