name: Build everything
run-name: Build everything from ${{ github.ref_name }} by @${{ github.actor }}
description: Assembler tous les paquets et la documentation au format html et pdf


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.14']

    steps:

      - name: installer python
        id: apt-py
        uses: actions/setup-python@v5
        if: ${{ always() }}
        with:
          python-version: '3.14'

      - name: installer pipenv
        id: pip-env
        run: python -m pip install pipenv
        if: ${{ always() }}

      - name: checkout repo
        id: checkout
        uses: actions/checkout@v4
        if: ${{ always() }}

      - name: installer le venv
        id: venv
        run: python -m pipenv install
        if: ${{ always() }}

      - name: créer le dossier d'assemblage
        id: dotbuild
        run: mkdir -p .github/.build
        if: ${{ always() }}

      - name: assembler sdist python
        id: sdist
        run: python -m pipenv run python -m build --sdist .github/.build
        if: ${{ always() }}

      - name: assembler wheel python
        id: wheel
        run: python -m pipenv run python -m build --wheel .github/.build
        if: ${{ always() }}

      - name: assembler module arduino
        id: arduino
        run: make -C .github arduino
        if: ${{ always() }}

      - name: compiler doc html
        id: doc-html
        run: python -m pipenv run sphinx-build -M singlehtml docs/src .github/.build
        if: ${{ always() }}

      - name: charger sdist python
        id: load-py
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: xphs1903-sdist
          path: .build/x_phs1903-*.tar.gz

      - name: charger wheel python
        id: load-wheel
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: xphs1903-wheel
          path: .github/.build/x_phs1903-*.whl

      - name: charger module arduino
        id: load-ard
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: xphs1903-arduino
          path: .github/.build/xphs1903.zip

      - name: charger doc
        id: load-doc
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: xphs1903-doc
          path: .github/.build/singlehtml
